# Generated by Django 4.1.7 on 2023-03-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='name',
            field=models.TextField(default='Key', verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='key',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Value'),
        ),
    ]
