# Generated by Django 4.1.7 on 2023-03-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DogImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('updated_ts', models.DateTimeField(auto_now=True, verbose_name='Updated Timestamp')),
                ('default_image', models.ImageField(upload_to='', verbose_name='Original Image')),
                ('modified_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Modified Image')),
                ('original_image_metadata', models.JSONField(default=dict, verbose_name='Original Image Metadata')),
            ],
        ),
    ]
